{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.fullname" . }}-clair-pg
  labels:
    app: {{ template "harbor.fullname" . }}-clair-pg
spec:
  ports:
    - port: 5432
  selector:
    app: {{ template "harbor.fullname" . }}-clair-pg
    release: {{ .Release.Name }}
{{ end }}